### ISSUE TITLE
Inverse kinematic solving

### ISSUE THREAD

**Issue by RyanJiao** [leap-hand/LEAP_Hand_API#3]
The fingers’s configuration don’t satisfy the Pieper-Criterion. I tried a few day to solve the analytical inverse kinematic but get nothing. Have you ever tried to derive the inverse kinematic solution of leap hand?

**Comment by Lucky7Chess** [comment]
Hi Ryan,

I haven't done IK specifically on LEAP hand because I use energy-function based approaches such as Robotic Telekinesis. I have used Pybullet IK to much success on robot arms such as xArm though.  Be careful to define your end-effector position properly on the fingertip mesh and then it should solve easily because this is only 4 DOF and not 6 DOF.

**Comment by RyanJiao** [comment]
Hi Kenny,

Sorry for bothering. I got the IK in the end. But I havn't figure out how to make sure whether the pose and position command I give to the finger is reachable or not, since the finger is only 4 DOF, in certain position the pose may be unreachable. I wander if you have come across this issue while using Pybullet IK. Many thanks.

**Comment by Lucky7Chess** [comment]
Yes this will happen with any IK-based method that there is a possibility there is no solution since it is out of the reachable workspace.   The IK solver will probably result with no solution. 

I don't think there's any fix for this really.  You could try randomly sampling joint angles first to define the reachable workspace of the fingertips.  Then command IK only if its within the volume of reachable areas.  Or allow for some sort of relaxation where you allow some part of the 6 DOF area to be not strictly specified like the rotation.  This leads back to energy function type approaches and more advanced IK which isn't the scope of the LEAP Hand paper and could be a good paper in itself.
